In [1]:
import time
import pymysql
from sqlalchemy import create_engine
import sqlalchemy
import numpy as np
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.keys import Keys

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC

In [2]:
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument("window-size=1200x600")

In [3]:
url = 'https://www.musinsa.com/app/contents/brandshop'
# def brand_scraping(url) :
wd = webdriver.Chrome('chromedriver', options=chrome_options)
wd.implicitly_wait(5)
wd.get(url)
df = pd.DataFrame(columns= ( "brand", "img"))
dataIdx = 0
i = 10
for j in range(1, 1000):
    print(j)
    try:
        brand = wd.find_element(By.XPATH, "/html/body/div[3]/div[3]/div[4]/div[%d]/ul/li[%d]/dl/dt/a"%(i, j)).text
        print(brand)
        wd.find_element(By.XPATH, "/html/body/div[3]/div[3]/div[4]/div[%d]/ul/li[%d]/dl/dt/a"%(i, j)).click()
        img = wd.find_element(By.XPATH, "/html/body/div[2]/div[3]/div[3]/div[1]/p[1]/img").get_attribute('src')
        df.loc[dataIdx] = [brand, img];
        wd.back()
        dataIdx += 1
    except:
        break;
    # return df

1
JAEGER-LECOULTRE
2
JERUSALEM SANDALS
3
JOHANSKEEM
4
JULGRAN
5
JOHNNY CARSON
6
JADIC
7
JAMAIVU
8
JAMINKYUNG
9
JABRA
10
JAVIN DE SEOUL
11
JAZBA
12
JAYEONPONG
13
JAUNKYEOL
14
JAIGURU DEVAOM
15
JACQUEMUS
16
JANDICREW
17
JANSPORT
18
JAMBANGEE
19
JAM'T
20
JEAN MICHEL BASQUIAT
21
JEAN PAUL GAULTIER
22
JEILIM
23
JACKNICKLAUS
24
JACK BLACK
25
JACK1T
26
JHONNY WEST
27
J'ASP
28
JACKAL
29
JOURNEY BUDDY
30
JUSTMOOD
31
JUST AS I AM
32
JUST CRAFT
33
JUSTHANG
34
JUNGSAEMMOOL
35
JENNER
36
JENNIFER LOPEZ
37
JENNYHOUSE COSMETIC
38
JEDREFEB5
39
JERRYBAG
40
JERRICAN
41
JEMUT
42
J.GRACELET
43
J.DAUL
44
J.W.ANDERSON
45
JW PEI
46
JADE M
47
JADEGOLDNINE
48
JADENCHUCK
49
JDX
50
J-RAHEL
51
J.LETTER
52
JROBE
53
JRIUM
54
J.LINDEBERG
55
JMARKNEWYORK
56
JAMIEWANDER
57
JAMIE WEST
58
JBANS CLASSIC
59
JBL
60
J VINEYARD
61
JAY'S WIFE
62
JCDC
63
JR SHAMPOO BAR
64
JANDLOO
65
J&MOLLS
66
JSSLOANE
67
JSNY
68
JESTINA
69
JHP139
70
JELEVE
71
JMW
72
JMK
73
J-ALL
74
J.JANE
75
JAYJUN
76
JKUSS
77
JT&CO
78
JAIN SONG
79
JAMES DEAN
80
JELLY MALLOW
81
JELLYPOP
82
JELLPANG
83
JEMKINS
84
JERSEY FACTORY
85
JO MALONE LONDON
86
JOEGUSH
87
JOGUMAN STUDIO
88
JORENZ CARTIESS
89
JORDAN
90
JOMA
91
JOSUNFIREWOOD
92
JOSEON TIGER
93
JOSEPH&STACEY
94
JOSEPHT
95
JOSLOUNGE
96
JOIE
97
JOY GRYSON
98
JOYMENT
99
JOYBEE
100
JOYSDAY
101
JOINTHEDANCE
102
JOJILONG
103
JOHNGYU
104
John Varvatos
105
JONES
106
JOHN PETERS
107
JOLIELAIDE
108
JOLYN
109
JONGNOGONGJANG
110
JONGJONG
111
JUNECI
112
JUNECI SPORTS CLUB
113
JOOLIFE NATURAL
114
JUMISO
115
JUAN HOMME
116
JUPAZIP
117
JUN BY JUN K
118
JUNEJUNE SPACE
119
JUNEHERITAGE
120
JULYME
121
JULYFOUR
122
JULIAPEPE
123
JEUNESSE
124
JEU DART
125
JEDE KONNEN
126
JUBINE
127
JUBILER
128
JUICE TO CLEANSE
129
JUICY COUTURE PERFUME
130
JUCYJUDY
131
JUANAYOON
132
JULIY&CALLA
133
JULIUS1
134
JLORIA
135
JINA IN NY
136
JINNY KIM
137
JIMMY CHOO
138
JIMIKO BLICO
139
JIU
140
JEEP
141
JEEP CAMPING
142
JIPRO
143
JEEPKIDS
144
JINJONJAM
145
JIL SANDER
146
JILGYUNGYI
147
JILL BY JILLSTUART
148
JILL BY JILLSTUART SHOES
149
JILL BY JILLSTUART KIDS
150
JILLSTUART MEN ACC
151
JILLSTUART SPORT NEWYORK
152
JILLSTUART ACC
153
JIPSY
154
JAVI
155

In [4]:
#complete
df

,brand,img
0,JAEGER-LECOULTRE,https://image.msscdn.net/mfile_s01/_brand/free...
1,JERUSALEM SANDALS,https://image.msscdn.net/mfile_s01/_brand/free...
2,JOHANSKEEM,https://image.msscdn.net/mfile_s01/_brand/free...
3,JULGRAN,https://image.msscdn.net/mfile_s01/_brand/free...
4,JOHNNY CARSON,https://image.msscdn.net/mfile_s01/_brand/free...
...,...,...
149,JILLSTUART MEN ACC,https://image.msscdn.net/mfile_s01/_brand/free...
150,JILLSTUART SPORT NEWYORK,https://image.msscdn.net/mfile_s01/_brand/free...
151,JILLSTUART ACC,https://image.msscdn.net/mfile_s01/_brand/free...
152,JIPSY,https://image.msscdn.net/mfile_s01/_brand/free...
153,JAVI,https://image.msscdn.net/mfile_s01/_brand/free...

In [5]:
df.to_csv("Data/brandJ.csv")